version: '2'
services:
  aggregatedb:
    image: mdillon/postgis
    volumes:
      - ./aggregatedb_data/postgresql:/var/lib/postgresql
      - ./aggregatedb_data/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
#      - ./aggregatedb_data/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    ports:
      - "5432:5432"
  aggregate:
    image: tomcat:8.0
    volumes:
      - ./aggregate_data/webapps:/usr/local/tomcat/webapps
      - ./aggregate_data/logs:/usr/local/tomcat/logs
    links:
      - aggregatedb
    ports:
      - "8080:8080"
